version: '3.8'
services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/:/backend/
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8000:8000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/static:/frontend/static
      - ./frontend/vite.config.js:/frontend/vite.config.js
      - ./frontend/svelte.config.js:/frontend/svelte.config.js
      - ./frontend/postcss.config.cjs:/frontend/postcss.config.cjs
      - ./frontend/tailwind.config.cjs:/frontend/tailwind.config.cjs
    command: npm run dev
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    depends_on:
      - backend
      - frontend
volumes:
  postgres_data:
